// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCioNpVTYoeKENSljoJJ40652DIJc7O5Qs',
    appId: '1:444726638413:web:a6b2b09302136a3a03a904',
    messagingSenderId: '444726638413',
    projectId: 'flutterfire-ui-codelab-ebad5',
    authDomain: 'flutterfire-ui-codelab-ebad5.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ebad5.appspot.com',
    measurementId: 'G-LTERN2008F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhYUHIGAFVv-h-Gl30LEB2uitXWEPSmI',
    appId: '1:444726638413:android:d97a4f02f432a01803a904',
    messagingSenderId: '444726638413',
    projectId: 'flutterfire-ui-codelab-ebad5',
    storageBucket: 'flutterfire-ui-codelab-ebad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsevhYQkJBoOlSvk_kj6a4oqoFCgWEkkY',
    appId: '1:444726638413:ios:225ba701b246d7ef03a904',
    messagingSenderId: '444726638413',
    projectId: 'flutterfire-ui-codelab-ebad5',
    storageBucket: 'flutterfire-ui-codelab-ebad5.appspot.com',
    iosClientId: '444726638413-1roljaei3cv3ccviq5nnkjq43l8afe22.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsevhYQkJBoOlSvk_kj6a4oqoFCgWEkkY',
    appId: '1:444726638413:ios:225ba701b246d7ef03a904',
    messagingSenderId: '444726638413',
    projectId: 'flutterfire-ui-codelab-ebad5',
    storageBucket: 'flutterfire-ui-codelab-ebad5.appspot.com',
    iosClientId: '444726638413-1roljaei3cv3ccviq5nnkjq43l8afe22.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
